In [ ]:
# Connect to SQLite database
connection = sqlite3.connect("library.db")  # Replace with your database file
cursor = connection.cursor()

# 1. Convert All Book Titles to Uppercase
query1 = """
SELECT Title, UPPER(Title) AS UppercaseTitle
FROM Books;
"""
cursor.execute(query1)
result1 = cursor.fetchall()
print("1. Convert All Book Titles to Uppercase:")
for row in result1:
    print(row)

# 2. Find Borrowers with Short Names (<= 5 characters)
query2 = """
SELECT Name
FROM Borrowers
WHERE LENGTH(Name) <= 5;
"""
cursor.execute(query2)
result2 = cursor.fetchall()
print("\n2. Find Borrowers with Short Names:")
for row in result2:
    print(row)

# 3. Count Books Borrowed Each Year
query3 = """
SELECT STRFTIME('%Y', BorrowedDate) AS BorrowYear, COUNT(*) AS BooksBorrowed
FROM BorrowedBooks
GROUP BY BorrowYear
ORDER BY BorrowYear;
"""
cursor.execute(query3)
result3 = cursor.fetchall()
print("\n3. Count Books Borrowed Each Year:")
for row in result3:
    print(row)

# 4. Find Overdue Books (Borrowed More Than 30 Days Ago)
query4 = """
SELECT BorrowedID, BookID, BorrowedDate
FROM BorrowedBooks
WHERE ReturnDate IS NULL
  AND (JULIANDAY('now') - JULIANDAY(BorrowedDate)) > 30;
"""
cursor.execute(query4)
result4 = cursor.fetchall()
print("\n4. Find Overdue Books (Borrowed More Than 30 Days Ago):")
for row in result4:
    print(row)

# 5. Find the Longest Book Title
query5 = """
SELECT Title, LENGTH(Title) AS TitleLength
FROM Books
ORDER BY TitleLength DESC
LIMIT 1;
"""
cursor.execute(query5)
result5 = cursor.fetchall()
print("\n5. Find the Longest Book Title:")
for row in result5:
    print(row)


# 7. Count Books Borrowed on Each Day of the Week
query7 = """
SELECT STRFTIME('%w', BorrowedDate) AS DayOfWeek, COUNT(*) AS BooksBorrowed
FROM BorrowedBooks
GROUP BY DayOfWeek
ORDER BY DayOfWeek;
"""
cursor.execute(query7)
result7 = cursor.fetchall()
print("\n7. Count Books Borrowed on Each Day of the Week:")
for row in result7:
    print(row)

# 8. Find the Most Common Day of the Week a Book Was Borrowed
query8 = """
SELECT STRFTIME('%w', BorrowedDate) AS DayOfWeek, COUNT(*) AS BooksBorrowed
FROM BorrowedBooks
GROUP BY DayOfWeek
ORDER BY BooksBorrowed DESC
LIMIT 1;
"""
cursor.execute(query8)
result8 = cursor.fetchall()
print("\n8. Find the Most Common Day of the Week a Book Was Borrowed:")
for row in result8:
    print(row)

# Close the connection
connection.close()